import warnings
from operations.train import train
from transformers import pipeline
from operations.train import args
import transformers
from typing import Dict

warnings.filterwarnings("ignore")

def generate_text(text: str) -> str:
    """A function that generates text from given prompt.

    Args:
        text (str): Text prompt.

    Returns:
        str: Text generated by the trained model. 
    """
    pipe = pipeline("text-generation", model="artifacts/checkpoint-2000")
    return pipe(text, num_return_sequences=2)[0]["generated_text"]

def train_model(args: transformers.TrainingArguments) -> None:
    """Initiates training process.

    Args:
        args (torch.TrainingArguments, optional): PyTorch TrainingArguments class containing all the points of customization for the model. Defaults to args.
    """
    # Train
    train(args, trial=False, optimize=False)




